title: Awesome Title

url: https://y7kim.github.io
baseurl: /agency-jekyll-theme-simple/
port: 4666
permalink: /:title/
encoding: utf-8

# Build settings
markdown: kramdown
include: ['_pages']
exclude: [.git, .gitignore, .sass-cache, README.md, jekyllbuild]


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

# prose.io
prose:
  media: 'img/portfolio'
  ignore:
    - .gitignore
    - _config.yml
    - _layouts
    - _includes
    - _plugins
    - css
    - js
    - mail
    - LICENSE
    - CNAME
    - README.md
    - index.html
    - style.css
    - feed.xml
    - img/favicons
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "nome da página"
      - name: "subtitle"
        field:
          element: "text"
          label: "subtitutlo do projeto"
      - name: "description"
        field:
          element: "textarea"
          label: "descrição curta do projeto"
      - name: "img"
        field:
          element: "text"
          label: "imagem de capa para o projeto"
          placeholder: "roundicons.png"
      - name: "modal-id"
        field:
          element: "number"
          label: "posição do projeto"
          placeholder: "6"
